name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    # ---------- toolchain ----------
    - name: Install asdf & plugins
      uses: asdf-vm/actions/install@v3
      with:
        submodules: false

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-v1

    # ---------- Rust workspace ----------
    - name: Cargo check
      run: cargo check --workspace --all-features

    # ---------- Foundry ----------
    - name: Set up Foundry
      run: |
        asdf exec foundryup -v nightly-2025-07-30
        forge --version

    - name: Forge build
      working-directory: contracts
      run: forge build --sizes

    # ---------- Gas fencing (250 SLOAD cap) ----------
    - name: Forge gas report guard
      working-directory: contracts
      run: |
        forge test --gas-report > gas.txt
        # Fail if any function exceeds 250 SLOADs
        if grep -E 'SLOAD:[[:space:]]+([2-9][5-9][1-9]|[3-9][0-9]{2,})' gas.txt; then
          echo "Gas guard breached (>250 SLOAD)"; exit 1
        fi

    # ---------- Node (optional front-end scripts) ----------
    - uses: actions/setup-node@v4
      with:
        node-version: 20.16.0
        cache: 'npm'
    - run: npm ci
      if: hashFiles('package.json') != ''

    # ---------- Lint formatting ----------
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-targets -- -D warnings
